### ISSUE TITLE
{@inheritdoc} is not used to detect exception annotation

### ISSUE THREAD

**Issue by roukmoute** [pepakriz/phpstan-exception-rules#17]
I think [`{@inheritdoc}`](https://docs.phpdoc.org/guides/inheritance.html) should be used to import exception annotation.

A simple example is to do a [command with Symfony](https://symfony.com/doc/current/console.html)

Exception is [marked here](https://github.com/symfony/symfony/blob/87adf25091568810e0d2996b17f9db25d9ee8147/src/Symfony/Component/Console/Command/Command.php#L155)

```php
/**
 * {@inheritdoc}
 */
protected function execute(InputInterface $input, OutputInterface $output): void
```

```
Unused @throws Symfony\Component\Console\Exception\LogicException annotation
```

**Comment by pepakriz** [comment]
I think the current behavior is correct. In your command class, you say it can throws `Symfony\Component\Console\Exception\LogicException` (because of `{@inheritdoc}`) but it is not true. Second thing - your implementation returns `void` which is incompatible with parent phpdoc. So you should remove phpdoc completely (native typehints are sufficient).

Maybe error message needs better wording - `@throws Symfony\Component\Console\Exception\LogicException annotation is unnecessary because the method body doesn't throw this class`

for all cases I'm gonna add test for `{@inheritdoc}`: https://github.com/pepakriz/phpstan-exception-rules/pull/18

**Comment by roukmoute** [comment]
I understand your logic.

But I don't think it is a good things to remove documentation for the benefit of the tools.

Is it not possible to _remove_ detected throw in parent when it is an overriden method?

**Comment by pepakriz** [comment]
I'm convinced that when your overridden method is more concrete, you should write custom concrete phpdoc (or use native hints). But I understand it is not so comfortable in some cases. I'll think about some new configuration option...

**Comment by Stadly** [comment]
This can probably be closed, now that `@throws void` is implemented. https://github.com/phpstan/phpstan/pull/2066

**Comment by marcospassos** [comment]
#95 introduces support for this use case.
